# Generated by Django 5.0.4 on 2024-04-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0002_remove_chair_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Driver', 'Driver'), ('Staff', 'Staff')], default='Customer', max_length=20),
        ),
        migrations.AlterField(
            model_name='pricet',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
